metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "change-es-host:5601"

output.elasticsearch:
  hosts: ["change-es-host:9200"]